name: flutter_user
description: "Flutter Userstory for onboarding, login, and registration."
version: 6.0.2
repository: https://github.com/Iconica-Development/flutter_user

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_input_library:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^3.7.0
  flutter_image_picker:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^4.1.0
  user_repository_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^6.0.0

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^7.0.0
